defaults: 
  - base_config
  - _self_
  - dataset: strict_small 
  - objective_curriculum: base_mlm

dataset: 
  name: 'CamBabyTrainers/BabyLM'

experiment: 
  seed: 42 

data_preprocessing:
  include_punctuation: True
  max_input_length: 128

trainer: 
  batch_size: 32 # across 4 GPUs gives an effective batch size of 128
  lr: 1e-4 # 1e-4 is used in fairseq; 1e-3 is default in huggingface
  num_warmup_steps: 30_000
  max_training_steps: 100_000
  eval_blimp: True
  eval_glue: False